backend:
  name: github
  repo: dantehemerson/dcweb 

media_folder: src/pages/posts/img/
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }