backend:
  name: github
  repo: dantehemerson/dcweb 

media_folder: src/pages/posts/img/
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: templateKey, widget: hidden, default: blog  }            
      - { label: Title, name: title,  }
      - { label: Description, name: description, widget: text}
      - { label: Path, name: path }
      - { label: "Featured Image", name: thumbnail, widget: image }
      - { label: Date, name: date,  widget: datetime }
      - { label: Body, name: body, widget: markdown }